language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - composer self-update
  - composer install

script: phpunit

notifications:
  email:
    - odolbeau@gmail.com
